# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getDataWithTwoForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_1(object):
    def setupUi(self, MainWindow_1):
        MainWindow_1.setObjectName("MainWindow_1")
        MainWindow_1.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_1)
        self.centralwidget.setObjectName("centralwidget")
        # Ghi dữ liệu form2
        self.pushWriteDataForm2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushWriteDataForm2.setGeometry(QtCore.QRect(150, 320, 131, 71))
        self.pushWriteDataForm2.setObjectName("pushWriteDataForm2")

        # Nhận dữ liệu Form 2
        self.pushGetDataForm2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushGetDataForm2.setGeometry(QtCore.QRect(450, 320, 131, 71))
        self.pushGetDataForm2.setObjectName("pushGetDataForm2")

        self.lineEdit_Form1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Form1.setGeometry(QtCore.QRect(270, 160, 211, 61))
        self.lineEdit_Form1.setObjectName("lineEdit_Form1")
        MainWindow_1.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_1)
        self.statusbar.setObjectName("statusbar")
        MainWindow_1.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_1)

        # self.pushGetDataForm2.setCheckable(True) #Nhận biết các trạng thái được nhấn và thả của nút nếu được đặt thành true   
        # self.pushGetDataForm2.toggle() 
        self.pushWriteDataForm2.clicked.connect(self.offForm1OnForm2)

        
        
    def retranslateUi(self, MainWindow_1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_1.setWindowTitle(_translate("MainWindow_1", "Form1"))
        self.pushWriteDataForm2.setText(_translate("MainWindow_1", "Show Form2"))
        self.pushGetDataForm2.setText(_translate("MainWindow_1", "GetDataForm2"))
    # Ghi dữ liệu vào form 2
    def offForm1OnForm2(self):
        
        Form2.show()
        Form1.hide()
        # self.getData1()
        # data1 = self.lineEdit_Form1.setText()
    
    
    


class Ui_MainWindow_2(object):
    def setupUi(self, MainWindow_2):
        MainWindow_2.setObjectName("MainWindow_2")
        MainWindow_2.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_2)
        self.centralwidget.setObjectName("centralwidget")
        self.pushGetData_Form2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushGetData_Form2.setGeometry(QtCore.QRect(150, 320, 131, 71))
        self.pushGetData_Form2.setObjectName("pushGetData_Form2")
        self.lineEdit_Form2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Form2.setGeometry(QtCore.QRect(110, 160, 211, 61))
        self.lineEdit_Form2.setObjectName("lineEdit_Form2")
        MainWindow_2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_2)
        self.statusbar.setObjectName("statusbar")
        MainWindow_2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_2)
        self.pushGetData_Form2.clicked.connect(self.getDataFromOfForm1)

    def retranslateUi(self, MainWindow_2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_2.setWindowTitle(_translate("MainWindow_2", "Form2"))
        self.pushGetData_Form2.setText(_translate("MainWindow_2", "GetDataForm1"))
    
    def getDataFromOfForm1(self):
        data1 = ui_1.lineEdit_Form1.text()
        self.lineEdit_Form2.setText(data1)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1 = QtWidgets.QMainWindow()
    ui_1 = Ui_MainWindow_1()
    ui_1.setupUi(Form1)
    Form1.show()

    Form2 = QtWidgets.QMainWindow()
    ui_2 = Ui_MainWindow_2()
    ui_2.setupUi(Form2)
    Form2.hide()

    sys.exit(app.exec_())
